### ISSUE TITLE
license function searches for Dart SDK license in wrong place when Homebrew'd

### ISSUE THREAD

**Issue by srawlins** [google/dart_cli_pkg#39]
I am assuming this is specific to Homebrew...

When Dart is installed with Homebrew, and running the `pkg-npm-dev` grinder task, I get the following crash:

```none
pkg-npm-dev
  writing build/npm/package.json
  copying build/abc.dart.js to build/npm

FileSystemException: Cannot open file, path = '/usr/local/Cellar/dart/2.7.1/libexec/LICENSE' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:594:18)
#4      license.<anon> (package:cli_pkg/src/utils.dart:94:52)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#7      license (package:cli_pkg/src/utils.dart:82:44)
#8      _buildPackage (package:cli_pkg/src/npm.dart:380:50)
#9      addNpmTasks.<anon> (package:cli_pkg/src/npm.dart:194:27)
```

Here are the various files in that Homebrew installation:

```none
~/code/abc/server:$ ls -FlAh /usr/local/Cellar/dart/2.7.1/libexec/
total 24
drwx------  15 sam  admin   510B Jan 23 05:07 bin/
-rw-r--r--   1 sam  admin   189B Jan 23 04:08 dartdoc_options.yaml
drwxr-xr-x   5 sam  admin   170B Jan 23 04:08 include/
drwxr-xr-x  29 sam  admin   986B Jan 23 04:11 lib/
-rw-r--r--   1 sam  admin    41B Jan 23 04:08 revision
-rw-r--r--   1 sam  admin     6B Jan 23 04:08 version

~/code/abc/server:$ ls -FlAh /usr/local/Cellar/dart/2.7.1/
total 24
drwxr-xr-x   3 sam  admin   102B Feb 20 21:15 .brew/
-rw-r--r--   1 sam  admin   584B Feb 20 21:15 INSTALL_RECEIPT.json
-rw-r--r--   1 sam  admin   1.5K Jan 23 04:05 LICENSE
-rw-r--r--   1 sam  admin   936B Jan 23 04:05 README
drwxr-xr-x  11 sam  admin   374B Feb 20 21:14 bin/
drwxr-xr-x   8 sam  admin   272B Feb 20 21:14 libexec/
```

**Comment by bohdanbirdie** [comment]
Can confirm, I also have this issue
Also installed via homebrew

**Comment by jathak** [comment]
It looks like this is due to Homebrew unpacking the Dart SDK in a non-standard way by putting the LICENSE file one directory up instead of in the main SDK directory.
